In [10]:
import pandas as pd
orderdetails = pd.read_csv("D:/coding ninja project git/E-commerce_company_case_study/datasets/orderdetails.csv")

In [11]:
orderdetails

,order_id,product_id,quantity,price_per_unit,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,1,1,3,15000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,3,2,8000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2,1,60000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7,2,40000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,3,7,3,40000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
514,199,3,1,8000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
515,199,1,1,15000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
516,200,5,2,5000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
517,200,2,2,60000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
518,200,6,3,7000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
orderdetails.isnull().sum()

order_id            0
product_id          0
quantity            0
price_per_unit      0
Unnamed: 4        519
Unnamed: 5        519
Unnamed: 6        519
Unnamed: 7        519
Unnamed: 8        519
Unnamed: 9        519
Unnamed: 10       519
Unnamed: 11       519
Unnamed: 12       519
Unnamed: 13       519
Unnamed: 14       519
Unnamed: 15       519
Unnamed: 16       519
Unnamed: 17       519
Unnamed: 18       519
Unnamed: 19       519
Unnamed: 20       519
Unnamed: 21       519
Unnamed: 22       519
Unnamed: 23       519
Unnamed: 24       519
Unnamed: 25       519
dtype: int64

In [17]:
orderdetails = orderdetails.dropna(axis=1,how='all')
orderdetails

     order_id  product_id  quantity  price_per_unit
0           1           1         3           15000
1           2           3         2            8000
2           3           2         1           60000
3           3           7         2           40000
4           3           7         3           40000
..        ...         ...       ...             ...
514       199           3         1            8000
515       199           1         1           15000
516       200           5         2            5000
517       200           2         2           60000
518       200           6         3            7000

[519 rows x 4 columns]

In [14]:
orders = pd.read_csv("D:/coding ninja project git/E-commerce_company_case_study/datasets/orders.csv")

In [15]:
orders

,order_id,order_date,customer_id,total_amount,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,1,2023-09-27,67,45000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2023-11-19,98,16000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2023-12-20,46,260000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,2023-04-29,83,27000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,2023-04-05,99,221000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,2023-04-16,87,126000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,197,2023-06-02,78,120000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,198,2023-09-17,60,151000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,199,2023-09-22,69,23000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,200,2023-06-15,4,151000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
orders.isnull().sum()

order_id          0
order_date        0
customer_id       0
total_amount      0
Unnamed: 4      200
Unnamed: 5      200
Unnamed: 6      200
Unnamed: 7      200
Unnamed: 8      200
Unnamed: 9      200
Unnamed: 10     200
Unnamed: 11     200
Unnamed: 12     200
Unnamed: 13     200
Unnamed: 14     200
Unnamed: 15     200
Unnamed: 16     200
Unnamed: 17     200
Unnamed: 18     200
Unnamed: 19     200
Unnamed: 20     200
Unnamed: 21     200
Unnamed: 22     200
Unnamed: 23     200
Unnamed: 24     200
Unnamed: 25     200
dtype: int64

In [23]:
orders = orders.dropna(axis = 1, how = 'all')
orders

     order_id  order_date  customer_id  total_amount
0           1  2023-09-27           67         45000
1           2  2023-11-19           98         16000
2           3  2023-12-20           46        260000
3           4  2023-04-29           83         27000
4           5  2023-04-05           99        221000
..        ...         ...          ...           ...
195       196  2023-04-16           87        126000
196       197  2023-06-02           78        120000
197       198  2023-09-17           60        151000
198       199  2023-09-22           69         23000
199       200  2023-06-15            4        151000

[200 rows x 4 columns]

In [24]:
products = pd.read_csv("D:/coding ninja project git/E-commerce_company_case_study/datasets/products.csv")

In [25]:
products

,product_id,name,category,price,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,1,"Smartphone 6""",Electronics,15000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,"Laptop 15"" Pro",Electronics,60000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Bluetooth Headphones,Electronics,8000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,E-Book Reader,Electronics,12000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Smartwatch Fitness Tracker,Wearable Tech,5000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,6,Portable Bluetooth Speaker,Electronics,7000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,7,Digital SLR Camera,Photography,40000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,8,Wireless Earbuds,Wearable Tech,3000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
products.isna().any()

product_id     False
name           False
category       False
price          False
Unnamed: 4      True
Unnamed: 5      True
Unnamed: 6      True
Unnamed: 7      True
Unnamed: 8      True
Unnamed: 9      True
Unnamed: 10     True
Unnamed: 11     True
Unnamed: 12     True
Unnamed: 13     True
Unnamed: 14     True
Unnamed: 15     True
Unnamed: 16     True
Unnamed: 17     True
Unnamed: 18     True
Unnamed: 19     True
Unnamed: 20     True
Unnamed: 21     True
Unnamed: 22     True
Unnamed: 23     True
Unnamed: 24     True
Unnamed: 25     True
dtype: bool

In [27]:
products = products.dropna(axis=1,how='all')

In [31]:
products

   product_id                        name       category  price
0           1               Smartphone 6"    Electronics  15000
1           2              Laptop 15" Pro    Electronics  60000
2           3        Bluetooth Headphones    Electronics   8000
3           4               E-Book Reader    Electronics  12000
4           5  Smartwatch Fitness Tracker  Wearable Tech   5000
5           6  Portable Bluetooth Speaker    Electronics   7000
6           7          Digital SLR Camera    Photography  40000
7           8            Wireless Earbuds  Wearable Tech   3000